--###################################################################
--Create Table of Members
--###################################################################
CREATE TABLE members(
    member_id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    gender CHAR(1) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR2(255) NOT NULL,
    PRIMARY KEY(member_id)
);

SELECT COUNT(member_id) FROM members;
--###################################################################
--To view all indexes of a table, you query from the all_indexes view:
--###################################################################
SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'MEMBERS';
    
--###################################################################
--Creating an index on one column example
--###################################################################
CREATE INDEX  i_members_last_name 
ON members(last_name);

SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'MEMBERS';
    
--###################################################################
--finds members whose last name is Harse:
--To check if a query uses the index for lookup or not, you follow these steps:
--First, add the EXPLAIN PLAN FOR clause immediately before the SQL statement:
--Then, use the DBMS_XPLAN.DISPLAY() procedure to show the content of the plan_table:
--###################################################################    
SELECT * FROM members
WHERE last_name = 'Harse';

EXPLAIN PLAN FOR
SELECT * FROM members
WHERE last_name = 'Harse';

SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());
    
--###################################################################
--Drop or Remove Index:
--###################################################################    
DROP INDEX   i_members_last_name;

--###################################################################
--Creating an index on multiple columns example:
--################################################################### 
CREATE INDEX members_name_i
ON members(last_name,first_name);

SELECT * 
FROM members
WHERE last_name LIKE 'A%' 
    AND first_name LIKE 'M%';
    
EXPLAIN PLAN FOR
SELECT * 
FROM members
WHERE last_name LIKE 'A%' 
    AND first_name LIKE 'M%';
   
SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());
    
    
    
    
